name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'master'
      - '[0-9]+.[0-9]+.x'
    tags:

env:
  default_php: 8.0
  stable_php: 8.1


jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x

  test-coverage:

    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: shivammathur/setup-php@2.30.5
        with:
          php-version: ${{ env.stable_php }}
          coverage: pcov
          ini-values: pcov.enabled=1
      - uses: "ramsey/composer-install@3.0.0"
      - run: php ./vendor/bin/phpunit --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false
          env_vars: PHP_VERSION
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  composer-require-checker:
    name: "Check for missing dependencies"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: shivammathur/setup-php@2.30.5
        with:
          php-version: ${{ env.stable_php }}
          ini-values: memory_limit=-1
          extensions: ${{ env.php_extensions }}
      - uses: "ramsey/composer-install@3.0.0"
      - run: composer global config bin-dir /usr/local/bin
      - run: composer global require -W maglnet/composer-require-checker
      - run: /usr/local/bin/composer-require-checker check
